### ISSUE TITLE
Error when creating new char with 3.0.8

### ISSUE THREAD

**Issue by ForthtuN** [brouznouf/fivem-mysql-async#51]
When creating new character with esx_identity/esx_skin as a new player, it spits out a large error. Only with the 3.0.8 version, not with anything below like 3.0.1 or 3.0.7. This makes the whole character creation menu never show up and you run around with no character

```
mysql-async.js:196862: Uncaught TypeError: Cannot read property '0' of null 
Error running call reference function for resource essentialmode: citizen:/scripting/lua/scheduler.lua:359: server/player/login.lua:9: attempt to index a boolean value (local 'user') 
stack traceback: 
server/player/login.lua:9: in upvalue 'ref' 
citizen:/scripting/lua/scheduler.lua:345: in function <citizen:/scripting/lua/scheduler.lua:344> 
[C]: in function 'xpcall' 
citizen:/scripting/lua/scheduler.lua:344: in function <citizen:/scripting/lua/scheduler.lua:343> 
stack traceback: 
[C]: in function 'error' 
citizen:/scripting/lua/scheduler.lua:359: in function <citizen:/scripting/lua/scheduler.lua:328> 
Error running call reference function for resource esplugin: citizen:/scripting/lua/scheduler.lua:359: citizen:/scripting/lua/MessagePack.lua:830: missing bytes 
stack traceback: 
[C]: in function 'error' 
citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow' 
citizen:/scripting/lua/MessagePack.lua:465: in field 'any' 
citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack' 
citizen:/scripting/lua/scheduler.lua:578: in upvalue 'Callback' 
server.lua:20: in upvalue 'ref' 
citizen:/scripting/lua/scheduler.lua:345: in function <citizen:/scripting/lua/scheduler.lua:344> 
[C]: in function 'xpcall' 
citizen:/scripting/lua/scheduler.lua:344: in function <citizen:/scripting/lua/scheduler.lua:343> 
stack traceback: 
[C]: in function 'error' 
citizen:/scripting/lua/scheduler.lua:359: in function <citizen:/scripting/lua/scheduler.lua:328> 
[91mError: Unhandled error: Error: BUFFER_SHORTAGE 
Error: BUFFER_SHORTAGE 
at n.e [as reserve] (citizen:/scripting/v8/msgpack.js:29:12766) 
at h (citizen:/scripting/v8/msgpack.js:29:15761) 
at n.r [as decode] (citizen:/scripting/v8/msgpack.js:29:13908) 
at n.fetch (citizen:/scripting/v8/msgpack.js:29:6972) 
at n.u [as read] (citizen:/scripting/v8/msgpack.js:29:12076) 
at Object.n [as decode] (citizen:/scripting/v8/msgpack.js:29:7097) 
at unpack (citizen:/scripting/v8/main.js:20:33) 
at citizen:/scripting/v8/main.js:51:11 
at setImmediate (mysql-async.js:4962:9) 
at Object.callback (citizen:/scripting/v8/timer.js:56:6)[0m 
SOURCE = 1 
mysql-async.js:196862: Uncaught TypeError: Cannot read property '0' of null 
[91mError: (node:32418) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object 
at Function.values (<anonymous>) 
at execute.then (mysql-async.js:5002:48) 
at process._tickCallback (internal/process/next_tick.js:188:7)[0m 
[91mError: (node:32418) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)[0m 
[91mError: (node:32418) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.[0m
 
```

**Comment by GHMatti** [comment]
Could you get the respective query so I can reproduce the error locally?

**Comment by ForthtuN** [comment]
Im sorry i have no idea how. This happens at the exact start of the game when a new player joins

**Comment by GHMatti** [comment]
Which server version are you on?

run it with `mysql_debug 1`
and you should see queries.

**Comment by GHMatti** [comment]
Seemingly no feedback on this, so it will be closed.
