### ISSUE TITLE
Error node 5276

### ISSUE THREAD

**Issue by MichaelEmond** [brouznouf/fivem-mysql-async#56]
Hello, I opened a server recently on Five M and when a player joins my server, it shows in my box error 5276, but the number changes every time I close. I would like to know what to do with that, I started again at 0 my server and the problem has not solved, here is what it shows me:

Error: (node:5276) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: unexpected PromiseRejectEvent
at process. (internal/process/promises.js:27:25)
at 
at Query.db.query [as _callback] (mysql-async.js:4973:13)
at Query.Sequence.end (mysql-async.js:280:24)
at Query.ErrorPacket (mysql-async.js:2122:8)
at Protocol._parsePacket (mysql-async.js:5941:23)
at Parser.write (mysql-async.js:6198:12)
at Protocol.write (mysql-async.js:5701:16)
at Socket. (mysql-async.js:693:28)
at emitOne (events.js:116:13)
Error: (node:5276) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Error: (node:5276) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: (node:5276) UnhandledPromiseRejectionWarning: Error: ER_NO_DEFAULT_FOR_FIELD: Field ‘pet’ doesn’t have a default value
at Query.Sequence._packetToError (mysql-async.js:244:14)
at Query.ErrorPacket (mysql-async.js:2109:18)
at Protocol._parsePacket (mysql-async.js:5941:23)
at Parser.write (mysql-async.js:6198:12)
at Protocol.write (mysql-async.js:5701:16)
at Socket. (mysql-async.js:693:28)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at addChunk (_stream_readable.js:263:12)
at readableAddChunk (_stream_readable.js:250:11)
--------------------
at Pool.query (mysql-async.js:4728:23)
at Promise (mysql-async.js:4970:12)
at new Promise ()
at execute (mysql-async.js:4967:26)
at Object.global.exports [as callback] (mysql-async.js:4985:5)
at citizen:/scripting/v8/main.js:87:41
at citizen:/scripting/v8/main.js:51:18
at setImmediate (mysql-async.js:4962:9)
at Object.callback (citizen:/scripting/v8/timer.js:56:6)
at onTick (citizen:/scripting/v8/timer.js:80:27)
Error: (node:5276) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
Error: (node:5276) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
at Function.values ()
at execute.then (mysql-async.js:5002:48)
Error: (node:5276) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

**Comment by murphyhf** [comment]
same problem

**Comment by MichaelEmond** [comment]
I resolved the problem murphy: in your PHPMyAdmin, delete all your essentialmode only and in your MySQL, delete your username. After, create a new essentialmode and reload all of your .SQL files. Reload your .SQL files into a new essentialmode and Bingo, your server is ok and all player who joined play and nothing problems showed on your box server.

**Comment by iProSENT** [comment]
Michael, can you make a video? I have the same problem.
The interesting thing is that I am doing a clean installation and still presents this error.

**Comment by MichaelEmond** [comment]
Me too i'm doing a clean installation. The problem is on PHPMyAdmin. Somethime, the essentialmode create an error with one files of your MySQL. Trying to find the problem is in my opinion more complicated, but install all of your .SQL files is simply. My wife go in my server right now after delete my essentialmode in PHP and i resolved the problem. After this, i don't know why it does not work!?!

Please note: My error and my problem create after a DDOS attack with a tierce person.
