### ISSUE TITLE
error at startup

### ISSUE THREAD

**Issue by iFusionFr** [brouznouf/fivem-mysql-async#64]
At times, the start fails. The server shows me the following error:

```
at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
    --------------------
    at Protocol._enqueue (mysql-async.js:5807:48)
    at Protocol.handshake (mysql-async.js:5714:23)
    at PoolConnection.connect (mysql-async.js:720:18)
    at Pool.getConnection (mysql-async.js:4577:16)
    at Pool.query (mysql-async.js:4731:8)
    at Promise (mysql-async.js:4970:12)
    at new Promise (<anonymous>)
    at execute (mysql-async.js:4967:26)
    at Object.global.exports [as callback] (mysql-async.js:4993:5)
    at citizen:/scripting/v8/main.js:87:41
Error: (node:4778) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
Error: (node:4778) UnhandledPromiseRejectionWarning: Error: Handshake inactivity timeout
    at Handshake.<anonymous> (mysql-async.js:5826:17)
    at emitNone (events.js:106:13)
    at Handshake.emit (events.js:208:7)
    at Handshake._onTimeout (mysql-async.js:321:8)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
    --------------------
    at Protocol._enqueue (mysql-async.js:5807:48)
    at Protocol.handshake (mysql-async.js:5714:23)
    at PoolConnection.connect (mysql-async.js:720:18)
    at Pool.getConnection (mysql-async.js:4577:16)
    at Pool.query (mysql-async.js:4731:8)
    at Promise (mysql-async.js:4970:12)
    at new Promise (<anonymous>)
    at execute (mysql-async.js:4967:26)
    at Object.global.exports [as callback] (mysql-async.js:4993:5)
    at citizen:/scripting/v8/main.js:87:41
Error: (node:4778) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
Error: (node:4778) UnhandledPromiseRejectionWarning: Error: Handshake inactivity timeout
    at Handshake.<anonymous> (mysql-async.js:5826:17)
    at emitNone (events.js:106:13)
    at Handshake.emit (events.js:208:7)
    at Handshake._onTimeout (mysql-async.js:321:8)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
    --------------------
    at Protocol._enqueue (mysql-async.js:5807:48)
    at Protocol.handshake (mysql-async.js:5714:23)
    at PoolConnection.connect (mysql-async.js:720:18)
    at Pool.getConnection (mysql-async.js:4577:16)
    at Pool.query (mysql-async.js:4731:8)
    at Promise (mysql-async.js:4970:12)
    at new Promise (<anonymous>)
    at execute (mysql-async.js:4967:26)
    at Object.global.exports [as callback] (mysql-async.js:4993:5)
    at citizen:/scripting/v8/main.js:87:41
Error: (node:4778) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
```

**Comment by RickvanO** [comment]
Same here

**Comment by GHMatti** [comment]
Any [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
