### ISSUE TITLE
Error Code Node (31523)

### ISSUE THREAD

**Issue by shadowoffice** [brouznouf/fivem-mysql-async#70]
Hello dear have recently create new server whit essentialmod and MYSQL async and esplugin_mysql and obtain erreur 

On Linux Ubuntu
have got all lasted version of ressouces is used on this config 

have my config here 

```
## Essential ##
start essentialmode
start mysql-async
start esplugin_mysql
set database_driver "mysql-async"
set mysql_slow_query_warning 50
set mysql_connection_string "mysql://favelasrp2011:Password@localhost/favelasrp2011"
set es_enableCustomData 1
start async

## From ESX Core ##
start cron
start es_extended

```

```
[91mError: (node:31523) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '3' of null
    at parseConnectingString (mysql-async.js:5049:30)
    at global.on (mysql-async.js:5067:18)
    at citizen:/scripting/v8/main.js:186:28[0m
[91mError: (node:31523) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)[0m
[91mError: (node:31523) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.[0m
WARNING: NON-EXISTENT NATIVE 000000004d52fe5b
[ERROR] [MySQL] [null] An error happens on MySQL for query "[object Object]": Cannot read property 'query' of undefined
[91mError: (node:31523) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'query' of undefined
    at Promise (mysql-async.js:4970:12)
    at new Promise (<anonymous>)
    at execute (mysql-async.js:4967:26)
    at global.exports (mysql-async.js:4993:5)
    at citizen:/scripting/v8/main.js:78:40[0m
[91mError: (node:31523) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)[0m
```

**Comment by schwim0341** [comment]
You have to move:
```
set mysql_connection_string "mysql://favelasrp2011:Password@localhost/favelasrp2011"
```
to the top of the page because ES requires it for the rest of the resources. Basically, you're telling ES to start and connect to the database before you ever give it the connection details.

Also move:
```
set es_enableCustomData 1
``` 
to the top of the page.

**Comment by shadowoffice** [comment]
Have try and got same error 👎

**Comment by shadowoffice** [comment]
Found error whit version 3.0.8 on linux want juste reset users mysql and use 
set mysql_connection_string "server=localhost;uid=favelasrp2011;password=Password;database=favelasrp2011"

**Comment by surajraj12** [comment]
Error: (node:27066) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 18)
How can I fix this?
