### ISSUE TITLE
Error code (node:19052) 

### ISSUE THREAD

**Issue by TomAvecLeVdsl** [brouznouf/fivem-mysql-async#71]
`Error: (node:19052) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 176.31.62.171:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
    --------------------
    at Protocol._enqueue (mysql-async.js:5807:48)
    at Protocol.handshake (mysql-async.js:5714:23)
    at PoolConnection.connect (mysql-async.js:720:18)
    at Pool.getConnection (mysql-async.js:4577:16)
    at Pool.query (mysql-async.js:4731:8)
    at Promise (mysql-async.js:4970:12)
    at new Promise (<anonymous>)
    at execute (mysql-async.js:4967:26)
    at Object.global.exports [as callback] (mysql-async.js:4993:5)
    at citizen:/scripting/v8/main.js:96:41
Error: (node:19052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Error: (node:19052) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

But i'v enter the good creditencial

**Comment by GHMatti** [comment]
Which version of mysql are you using. With just an error, you cannot be helped.

Mysql, MariaDB, etc. How do I replicate an error and fix it, if I do not know anything about it.

**Comment by TomAvecLeVdsl** [comment]
it's just was because i was using a mysql server on another computer , when i move the mysql server on the hosting machine , it was working :)

**Comment by GHMatti** [comment]
Okay thanks.
