### ISSUE TITLE
Emoji in player name throwing mysql errors

### ISSUE THREAD

**Issue by RikoDEV** [brouznouf/fivem-mysql-async#82]
```
[ERROR] [MySQL] [esx_anticheat] An error happens on MySQL for query "INSERT INTO baninfo (identifier,license,liveid,xblid,discord,playerip,playername) VALUES ('steam:<censored>','license:<censored>','brak','brak','discord:<censored>','ip:<censored>','👈♔Player♔👉')": ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x91\x88\xE2\x99...' for column `s01_database`.`baninfo`.`playername` at row 1
Error: (node:19) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: unexpected PromiseRejectEvent
at process.<anonymous> (internal/process/promises.js:27:25)
at <anonymous>
at Query.db.query (mysql-async.js:5223:9)
at Query.<anonymous> (mysql-async.js:1117:10)
at Query._callback (mysql-async.js:1083:16)
at Query.Sequence.end (mysql-async.js:275:24)
at Query.ErrorPacket (mysql-async.js:2237:8)
at Protocol._parsePacket (mysql-async.js:6296:23)
at Parser._parsePacket (mysql-async.js:6907:10)
at Parser.write (mysql-async.js:6517:10)
Error: (node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
Error: (node:19) UnhandledPromiseRejectionWarning: Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x91\x88\xE2\x99...' for column `s01_database`.`baninfo`.`playername` at row 1
at Query.Sequence._packetToError (mysql-async.js:239:14)
at Query.ErrorPacket (mysql-async.js:2224:18)
at Protocol._parsePacket (mysql-async.js:6296:23)
at Parser._parsePacket (mysql-async.js:6907:10)
at Parser.write (mysql-async.js:6517:10)
at Protocol.write (mysql-async.js:6043:16)
at Socket.<anonymous> (mysql-async.js:683:28)
at Socket.<anonymous> (mysql-async.js:1117:10)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
--------------------
at Pool.query (mysql-async.js:4910:23)
at Promise (mysql-async.js:5220:10)
at new Promise (<anonymous>)
at MySQL.execute (mysql-async.js:5216:26)
at Object.global.exports [as callback] (mysql-async.js:5101:9)
at citizen:/scripting/v8/main.js:96:41
at citizen:/scripting/v8/main.js:51:27
at setImmediate (mysql-async.js:14901:7)
at Object.callback (citizen:/scripting/v8/timer.js:96:21)
at onTick (citizen:/scripting/v8/timer.js:121:27)
Error: (node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
```

**Comment by pelikaanjpeg** [comment]
This has to do with the unicode version I think. First thing to check is to see if your users table is using utf8mb4 and not utf8 and then you'd have to switch the mysql plugin to utf8mb4 (not entirely sure how to do it but you can specifiy it in the connection string somehow)

**Comment by GHMatti** [comment]
default is `charset=utf8_general_ci`, add
`charset=utf8mb4_general_ci` to your connection string.
