### ISSUE TITLE
Server keeps crashing after update 3.1.1 -> 3.2.0

### ISSUE THREAD

**Issue by DylanArens** [brouznouf/fivem-mysql-async#86]
Hi,

I've updated the mysql-async script of my server from version 3.1.1 to 3.2.0 but my server keeps crashing now while it worked just fined before the update.

Error:
```Error calling system call ref function in resource mysql-async: TypeError: Cannot read property 'execute' of null
stack:
TypeError: Cannot read property 'execute' of null
    at Object.global.exports [as callback] (mysql-async.js:4945:9)
    at citizen:/scripting/v8/main.js:96:41
Error resuming coroutine: citizen:/scripting/lua/scheduler.lua:720: An error happened while calling export mysql_fetch_scalar of resource mysql-async (citizen:/scripting/lua/MessagePack.lua:830: missing bytes), see above for details
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:720: in method 'mysql_fetch_scalar'
        @mysql-async/lib/MySQL.lua:161: in field 'fetchScalar'
        @mudoogaming/account/whitelist_server.lua:16: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:169: in function <citizen:/scripting/lua/scheduler.lua:168>```

**Comment by DylanArens** [comment]
Nvm, doing hwat you suggested in #74 fixed it.
